function visualize_monte_carlo_check(Results, model_type, sim_idx, save_path)
%% FUNCTION DESCRIPTION
% Plots and optionally saves MC check (confirm that rho actually has an
% impact on the data generating process)
%
% INPUTS:
%   Results    : Results structure generated by simulation script
%   model_type : 'Mean' or 'Vol' (Default: 'Mean')
%   sim_idx    : Index of the simulation iteration to plot (Default: 1)
%   save_path  : (Optional) Filename or path to save the image (e.g. 'Plot.png')
%                If set to true (boolean), saves with a default name.

    %% 1. Argument Handling
    if nargin < 2 || isempty(model_type), model_type = 'Mean'; end
    if nargin < 3 || isempty(sim_idx), sim_idx = 1; end

    % Identify available pairs in the structure
    f_names = fieldnames(Results);
    n_pairs = length(f_names);

    %% 2. Visualization
    % Create figure and store handle 'fig' for saving later
    fig = figure('Name', sprintf('Monte Carlo Check: %s Model (Sim #%d)', model_type, sim_idx), ...
                 'Color', 'w', 'Units', 'normalized', 'Position', [0.1 0.1 0.5 0.8]);

    for p = 1:n_pairs
        field_name = f_names{p};
        
        % Extract the relevant 3D matrix (Mean or Vol)
        if strcmpi(model_type, 'Vol')
            Data3D = Results.(field_name).Vol;
        else
            Data3D = Results.(field_name).Mean;
        end
        
        % Extract specific slices
        % Rho indices: 1 corresponds to rho=0 (Exog), end corresponds to rho=-1 (Endo)
        Y_exo  = Data3D(:, sim_idx, 1);   
        Y_endo = Data3D(:, sim_idx, end); 
        
        % Plotting logic
        subplot(n_pairs, 1, p);
        plot(Y_exo, 'b', 'LineWidth', 1); hold on;
        plot(Y_endo, 'r--', 'LineWidth', 1);
        
        % Extract alpha for title
        curr_alpha = Results.(field_name).Alpha;
        
        title(sprintf('%s Model (%s: \\alpha=%.1f) - Sim #%d', ...
            model_type, field_name, curr_alpha, sim_idx), 'Interpreter', 'tex');
        
        if p == 1
            legend('Exogenous (\rho=0)', 'Endogenous (\rho=-1)', 'Location', 'best');
        end
        axis tight; grid on;
        ylabel('Value');
    end
    
    xlabel('Time Observations');

    %% 3. Auto-Save Logic
    if nargin >= 4 && ~isempty(save_path)
        % If user passed 'true' (boolean), generate a default filename
        if islogical(save_path) && save_path
            save_path = sprintf('MonteCarlo_%s_Sim%d.png', model_type, sim_idx);
        end
        
        % Ensure string type
        if ischar(save_path) || isstring(save_path)
            try
                % Use exportgraphics (Modern MATLAB) or saveas (Legacy)
                if exist('exportgraphics', 'file')
                    exportgraphics(fig, save_path, 'Resolution', 300);
                else
                    saveas(fig, save_path);
                end
                fprintf('>> Chart automatically saved to: %s\n', save_path);
            catch ME
                warning('Could not save chart: %s', ME.message);
            end
        end
    end
end